templates/fragments/js/twitter/widgets.html

See: https://dev.twitter.com/web/javascript/loading

add accidentally removed twitter widgets js stub

---

apps/accounts/forms/settings.py
apps/accounts/social_auth_pipeline.py
templatetags/gravatar.py

- social auth - strategy.request instead of just request
- use display name for gravatar templatetag alt
- remove unnecessary model def/lookup

Django 1.8 upgrade fixes

---

apps/accounts/constants/defaults.py
apps/accounts/emails.py
apps/accounts/forms/auth.py
apps/accounts/utils/general.py
constants/defaults.py
mailers.py

- parameterized email subject lines
- add setting to activate accounts upon registration, HTK_ACCOUNT_ACTIVATE_UPON_REGISTRATION
- fix get_user_by_email, associate_user_email
- ability to attach files/images to emails (although, for reputation purposes, still better to link externally)

lots of improvements to emails and accounts

---

forms/classes.py

slight performance improvement to AbstractModelInstanceUpdateForm and clean up code

---

apps/accounts/social_auth_pipeline.py
apps/accounts/view_helpers.py
test_scaffold/tests.py
utils/s3.py

- Changed test_scaffold to consider `secure` parameter for `https` redirection
- Updated social authentication pipeline functions

test_scaffold and social auth pipeline

---

lib/stripe_lib/admin.py
lib/stripe_lib/models.py

- change name to nickname field
- remove statement_description field
- include product_id in create

update BaseStripePlan model

---

lib/oembed/utils.py

Autoplay defaults to false, so it should work with existing code.

Adds default autoplay argument and handles youtube

---

admintools/models.py
static/htk/js/toolbar/emulate_user.js
templates/htk/fragments/toolbar/base.html
templates/htk/fragments/toolbar/emulate_user.html

HTK/CSS PR: https://github.com/hacktoolkit/htk-css-hacktoolkit/pull/1
Talentral PR: https://github.com/talentral/www/pull/934

Emulate User

---

apps/organizations/models.py

change Organization.get_members to return queryset

---

templates/htk/fragments/messages.html

maskil PR: https://github.com/jontsai/maskil-www/pull/29

Add messages to htk

---

templatetags/htk_tags.py

Add has_permission simple_tag

---

apps/mp/__init__.py
apps/mp/apps.py
apps/mp/services.py
apps/mp/signals.py
apps/mp/tasks.py
apps/mp/utils.py
utils/queryset_iterators.py

- computed properties can be stored as a field on the table/row

add materialized property app for DB performance optimization

---

lib/stripe_lib/models.py
lib/stripe_lib/utils.py

- return None if no subscription_id passed into retrieve_subscription
- cleanup logging
- remove incorrect/unused try/except

fix/update Stripe lib utils

---

utils/text/transformers.py

Added preserve_extended_ascii to seo_tokenize

Fixed ASCII replacement

---

extensions/data_structures/__init__.py
extensions/data_structures/ordered_set.py

```
In [1]: from htk.extensions.data_structures import OrderedSet
In [2]: os = OrderedSet(['c', 'a', 'b'])
In [3]: list(os)
Out[3]: ['c', 'a', 'b']
In [4]: os = OrderedSet(['c', 'a', 'b', 'a', 'b', 'b', 'b'])
In [5]: list(os)
Out[5]: ['c', 'a', 'b']
In [6]: s = set(['c', 'a', 'b', 'a', 'b', 'b', 'b'])
In [7]: list(s)
Out[7]: ['a', 'c', 'b']
```

adds OrderedSet data structure

---

apps/accounts/models.py
apps/addresses/admin.py
apps/addresses/models.py
apps/bible/models.py
apps/cpq/admin.py
apps/cpq/models.py
apps/customers/models.py
apps/feedback/models.py
apps/forums/models.py
apps/geolocations/admin.py
apps/invitations/models.py
apps/organizations/models.py
apps/prelaunch/models.py
apps/store/models.py
apps/url_shortener/models.py
constants/i18n/greetings.py
lib/github/bots.py
lib/gravatar/utils.py
lib/literalword/utils.py
lib/oembed/utils.py
lib/plivo/constants/general.py
lib/qrcode/utils.py
lib/stripe_lib/models.py
lib/yahoo/sports/fantasy/client.py
lib/yahoo/sports/scripts/download_player_ids.py
templatetags/htk_tags.py
templatetags/urlizer.py
utils/text/transformers.py
utils/text/unicode.py

Py3 upgrade encoding

---

test_scaffold/tests.py

Added HTTP handles to process put and delete requests.
Reference PR: [1267](https://github.com/talentral/www/pull/1267)

Add handles for HTTP PUT and DELETE

---

apps/accounts/forms/update.py

Added timezone form to store timezone in the user profile.
Reference PR https://github.com/talentral/www/pull/1273
https://trello.com/c/a91sS3IA

Added user timezone form

---

apps/accounts/forms/update.py

**READY**
Updated the user timezone choices.
https://trello.com/c/ngUFq7PT

Updated timezone choices

---

utils/text/__init__.py
utils/text/algorithms.py

**READY**
Added get_closest_dict_words function to get top matches using Levenshtein distance for Word Autocompletion and Autocorrection algorithm

Added get_closest_dict_words function to get top matches

---

lib/dynamic_screening_solutions/api.py

**READY**
Added error handle to webhook topics.

Add error handle for webhook topics

---

apps/accounts/constants/defaults.py
apps/accounts/forms/auth.py

**READY**
Fixed the issue of resend email confirmation broken link. Fixed lint issues.

Fix broken link of resend email confirmation

---

lib/ziprecruiter/api.py

ZipRecruiter Job posting using API
https://www.ziprecruiter.com/partner/documentation/#job-api-operations

Added ZipRecruiter Job API handles

---

apps/addresses/models.py

Added `Neighborhood` field in `BasePostalAddress`

Add Neighborhood field in BasePostalAddress

---

apps/organizations/models.py

Defines `json_encode()` methods for both members and invitation models of Organization app.

Adds `json_encode` for Organization members and invitations.

---

templates/fragments/js/rollbar/rollbar.html
templates/fragments/js/rollbar/v2.25.x.html

Adds new Rollbar JS release to stack.
Refs:
https://github.com/rollbar/rollbar.js/releases/tag/v2.25.0

Adds Rollbar JS v.2.25

---

apps/organizations/models.py

**READY**
Changes `NullBooleanField` to `BooleanField(null=True)`.
This field is deprecated in Django 3.x and removed in Django 4.x
This is a bugfix
This field was causing a warning on migrations. Changing this will fix those warnings.
Deploy to these machines:
**Requires Migration: YES**
**Requires Data Backfill: NO**
`venv/bin/python manage.py makemigrations --name alter_accepted_field_on_base_abstract_organization_invitation [app-name]`
`venv/bin/python manage.py migrate [app-name]`

Change deprecated NullBoleanField to BooleanField

---

lib/aws/s3/__init__.py
lib/dynamic_screening_solutions/api.py

These are giving errors while testing on Python3 environment.
I have used this documentation on porting Python Standard Library imports: https://docs.python.org/3/howto/pyporting.html

Fix imports

---

lib/stripe_lib/models.py

Fixed issue with Stripe Subscription

Fix Stripe Subscription issues

---

lib/stripe_lib/models.py

Fix the issue `KeyError` raised while fetching `card` details of `Stripe Customer`

Fix the exception Key Error

---

lib/stripe_lib/models.py

Provide support for `unicode` type subscription data

Add support to unicode type for Subscription data

---

lib/aws/s3/models.py

Fixed issue of cloning picture asset in S3

Fix issue with cloning picture asset

---

lib/dynamic_screening_solutions/api.py

READY
Fixed issues with 321Forms API responses

Fixed issues with 321Forms API response

---

utils/enums.py

Add HtkEnum for using as Abstract Enum. Allows easily encoding Enum to JSON

Add HtkEnum class

---

apps/features/views.py
templates/htk/fragments/features/admin.html

- Allow `features_view` to accept `template`, `renderer` and `data` variables
- API URL name in template made dynamic

Update `features_view` on features app

---

lib/stripe_lib/models.py

READY
Fix issues with fetching stripe card

Fix issue with fetching stripe card

---

apps/prelaunch/models.py

Add missing return statement to `htk.apps.prelaunch.models.PrelaunchSignup.get_or_create_by_email` classmethod

Add return statement to PrelaunchSignup.get_or_create_by_email

---

apps/features/decorators.py

Added a new decorator to `htk.apps.features` to easily disable the desired view if feature is disabled.

✨ Add require_feature_enabled decorator for views

---

constants/i18n/greetings.py

**Ethiopian official language Amharic is Added as one of the greetings list.**

Ethiopian Amharic greeting added to greetings list.

---

apps/tokens/utils.py

This changes enables adding extra filters when using `Model.objects.get` method. `get_token` method  should be able to filtered according to needs.
Backwards compability:
This changes do not affect the places using these methods.

Add kwargs to token methods

---

apps/mp/services.py

`depend_on` parameter of `mp.materialized_property` was only working with forwarded relations.
**Explanation**
Taking below example of model relations:
```python
class Profile(models.Model):
user = models.OneToOneField(settings.AUTH_USER_MODEL, related_name='profile')
class Asset(models.Model):
user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='assets')
is_active = models.BooleanField(default=True)
```
If we want to create a `materialized_property` in `Profile` class for `Asset` count, it wouldn't work because `User` model has no explicit field definition for asset:
```python
class Profile(models.Model):
@mp.materialized_property(
models.PositiveIntegerField(blank=True),
depends_on=['user.assets.is_active', ],  # This wouldn't work before
)
active_asset_count(self):
``` …

✨ feat: add support to reversed relations on materialized_property depends_on

---

templates/fragments/js/rollbar/rollbar.html
templates/fragments/js/rollbar/v2.26.x.html

Adds Rollbar browser JS v2.26.x snippet
Docs: http://rollbar.com/
Source: https://github.com/rollbar/rollbar.js/releases

Adds Rollbar v2.26.x JavaScript snippet

---

utils/datetime_utils.py

Added `tz` as keyword argument to `fromtimestamp`, a method of `datetime.datetime`.

Add keyword argument tz

---

lib/stripe_lib/models.py

Added functions to `list invoice items` and `delete pending invoice items`.

List invoice items and Delete pending invoice items 

---

apps/mp/services.py

`htk.apps.mp.services.parse_dependency` function is updated to work correctly on Django versions 2.x, 3.x and 4.x

feat: ⚡️ Improve MP dependency parser for Django >=2

---

lib/stripe_lib/models.py

This PR adds Stripe API's to list invoices.

Stripe API's to list invoices

---

apps/organizations/forms.py

**READY**
Added forms for Organization Team and Organization Team Member

feat: ✨ Add Organization Team and Team Member forms

---

api/utils.py

**READY**
Added API Utility function to response form errors in API endpoints.

feat(API): ✨ Add json_response_form_error API util function

---

api/utils.py
decorators/classes.py
utils/text/transformers.py

**READY**
- Added `resolve_records_from_restful_url` decorator which tries to find the records from path arguments in a chained way.
- Adds `pascal_case_to_snake_case` text transformer util.

feat(decorator): ✨ Resolve records from URL

---

utils/csv_utils.py

**READY**
- Fixed bad output file on Python 3 and ensured Python 3 does not use `UnicodeEncoder`

fix: 🐛 Fix CSV utility to make it Python 2 and 3 compatible

---

utils/image.py

Fixed issue of no module named `StringIO`

Fix module not found error - StringIO

---

utils/text/sanitizers.py

- Adds `sanitize_cookie_value` utility function.

feat(utils): ✨ add cookie value sanitizer

---

apps/assessments/enums.py
apps/assessments/models.py
apps/assessments/utils.py

Add abstract models for Assessment.

Add abstract Assessment models

---

apps/accounts/forms/settings.py
apps/accounts/forms/update.py

Ready
Add user email update feature

Add Manual confirm for UserEmail while adding new verified Email.

---

apps/forums/admin.py
apps/forums/fk_fields.py
apps/forums/models.py
apps/organizations/fk_fields.py
apps/organizations/models.py
models/fk_fields.py

- Changes the `timestamp` list_display field to `posted_at` in alignment with the `ForumThread` model.
- Adds `ForumTag` admin.
- Adds `fk_fields` for `organziation` and `user`.

fix: 🔧 ♻️ refactors `organizations` and `forums` models

---

apps/organizations/models.py

- adds `create_with_owner`
- fix `add_owner`

improvements to Organizations

---

apps/conversations/models.py

- Adds model instance methods to remove a single participant or multiple participants from a conversation.

feat: ✨ adds `remove_participant(s)` to the `Conversation` model

---

apps/accounts/views.py

- Implement a custom model for social registration and authentication that allows for easy modification of form field classes.

Provide a custom form class for social register

---

lib/google/youtube/constants.py
lib/google/youtube/utils.py

Obtain `video duration` of `YouTube URL` using `Google API`.

YouTube video duration using Google API

---

apps/conversations/fk_fields.py

- Adds a foreign key for a `conversation participant` for any references to child models with the `conversation participant` foreign key `related name` field.

feat: ✨ adds `ConversationParticipant fk_field` to `BaseConversation`s

---

apps/assessments/enums.py

Added additional Question Types.

Add additional question types

---

apps/assessments/models.py

Add field `is_enabled` in `AbstractAssessmentQuestion` model.

Add field in Assessment Question model 

---

apps/assessments/models.py

Fix inconsistent field name in Assessment model.

Fix field name inconsistency in Assessment model

---

apps/accounts/views.py
apps/mobile/constants/defaults.py
constants/defaults.py

Ready
Add a mobile deep link option on resetting password

feat ✨ Reset password mobile

---

apps/bible/models.py

This PR introduces a new feature that allows users to view all verses from a specified reference to the end of the chapter by appending the suffix 'ff' to the verse reference.
Uses a recursive approach to resolve the passage when the 'ff' suffix is present.

feat: ✨ Add Support for 'ff' Suffix to Display Verses Until End of Chapter

---

apps/accounts/constants/social.py

This PR adds the Apple ID social auth description to the `SOCIAL_AUTHS` constant.

feat: ✨ adds apple id in social auth constant

---

apps/forums/fk_fields.py

- Adds a method to resolve the foreign key for forum messages.

feat: ✨ adds a new `fk` definition forum messages

---

utils/measurements/distance.py

- Adds the `cm` and `mm` properties on the `DistanceType` to conveniently convert a `DistanceType` instance in meters to one of the available units directly through a property.

feat: ✨ adds cm and mm conversion from meters

---

lib/mapbox/geocode.py

- Refactors the MapBox API response into its own function and returns the first accurate response in the `features` key. 
- Adds a method to return `context` data from the response in a dictionary for ease of access.
- https://docs.mapbox.com/api/search/geocoding

feat: ✨ refactors mapbox API response

---

lib/fitbit/api.py
lib/fitbit/utils.py

Add handling to prevent a user NoneType assignment error from emerging when displaying or using the FitBitAPI

fix 🔧  add user NoneType handling

---

apps/blob_storage/models.py
utils/http/__init__.py
utils/http/response.py

Added CORS headers and a general cache function in HTK to clean up repeated code on both the HTK and Django sides.

fix: 🔧  added cors headers and cache general function
