hacktoolkit/django-htk

- api/utils.py
- `s/CustomJSONEncoder/HtkJSONEncoder/` and use DjangoJSONEncoder as base
- `json_response_error` allows custom data and 400 status code by default
> various json response improvements

- lib/dynamic_screening_solutions/api.py
- more detailed error logging when users cannot be retrieved
- response.json() instead of json.loads(response.text)
>  more detailed error logging when users cannot be retrieved

- admintools/middleware.py
@jontsai We are messaging all the time for user's that aren't allowed to emulate. They should just simply pass through the middleware.
> Remove message when user is not allowed to emulate

- apps/accounts/models.py
**READY**
Fixed the issue raised when `UserEmail` object is `None` and added more log to get the user details and to find the exact cause of receiving none object on triggering activation remainder emails..
> Fixed issue and added more info in rollbar on triggering activation remainder emails

- apps/tokens/utils.py
Fixed issue in getting valid token when a token object doesn't exist
> Fixed issue in getting valid token when token object doesn't exist

- templates/fragments/js/rollbar/rollbar.html
- templates/fragments/js/rollbar/v2.24.x.html
According to changelog and documentation,
`hostBlackList` changed to `hostBlockList` and
`hostWhiteList` changed to `hostSafeList`
with `v2.20.0` in terms of configuration.
Refs:
https://github.com/rollbar/rollbar.js/releases/tag/v2.20.0
https://docs.rollbar.com/docs/javascript#upgrading-from-previous-versions
> Adds Rollbar.js v2.24 to the stack

- lib/stripe_lib/models.py
Makes the model `BaseStripeSubscription` as `Abstract`
> Make BaseStripeSubscription model Abstact

- lib/stripe_lib/models.py
Fixed issues with cancelling stripe subscription(missing `subscription_id`) and listing stripe charges(variable mismatch)
> Fix issues with cancelling subscription and listing charges

- apps/prelaunch/migrations/0001_initial.py
The prelaunch model's fields have been changed but the migrations was not updated.
This was causing fail on tests.
> Add missing fields on prelaunch model to migration

- templates/htk/fragments/features/admin.html
- Features app toggle modal now shows Feature title as well as Feature name (unformatted)
- Feature name is being shown with `monospace` font.
Example: The Feature **Test Feature** (test_feature) will be **Enabled**.
Additional changes:
- All CSS definitions prefixed with `.features-app` to prevent breaking other elements
- Modal getting feature name and title from `data-name=""` and `data-title=""` attributes of `<h3 />` tag instead of text.
> 🎨 Add feature name to modal text

- templates/htk/fragments/features/admin.html
- Fixed typo on `.feature-name` class
- Fixed exclamation mark align.
> 🩹 Fix typo and exclamation mark align on features view styling

- templates/htk/fragments/features/admin.html
- Fix close button on toggle modal (it was buggy on projects using bootstrap 5.2 CSS framework)
- Fix feature name not being monospace font.
> Fix close button and monospace feature_name on modal

- templates/htk/fragments/features/admin.html
**The on/off toggle extends outside of the box if the feature flag name is too long.**
> Feature flag toggler outlier fix

- templates/htk/fragments/features/admin.html
Fixed responsive styling problems on Feature Flag page.
- If screen size is `>= 1400px` it will show `3` columns
- If screen size is `>= 1200px` it will show `2` columns
- If screen size is  `< 1200px` it will show `1` column
> 💄🩹 fix: styling response problems on feature flag page

- apps/mp/services.py
`related_name` was setting wrong name in reversed related name while parsing dependencies.
This PR fixes it.
> Fix related_name while parsing dependencies on MP

- apps/prelaunch/models.py
`PrelaunchSignup.get_or_create_by_email` method now works correctly even if there are multiple records with same email address.
If there are same records which early access enabled for them, it picks it over other ones.
> Add guard to prelaunch get_or_create_by_email method

- lib/dynamic_screening_solutions/api.py
Currently, if api response is error handled to return `response_json` as `None`.
In this PR I handled to return error response so that user can be warned with the actual issue reported.
And also in Rollbar, the actual error will get reported.
> Return api error response

- lib/stripe_lib/models.py
Currently remove subscription return value is hard coded instead of processing from Stripe cancel api response.
> Fix remove subscription return value

- apps/organizations/apps.py
- apps/organizations/models.py
- apps/organizations/views.py
Updates the signal handler for `OrganizationInvitation` to send a Slack notification when an invitation is created, re-sent, accepted, or declined.
> update OrganizationInvitation signal handler for sending Slack messages

- utils/js_route_serializer.py
**READY**
Due to a code structure, the namespaced routes names were generated like `namespace:none:urlName`.
This update fixes it and the output is corrected to `namespace:urlName`
> fix(JS Routes): 🐛 Fix serializer namespace defining

- apps/mp/services.py
- lib/zillow/zestimate.py
- lib/zillow/zillow_types.py
**READY**
Patches `basestring` to make Python3 compatible
> fix: 🐛 basestring patch for python3

- utils/csv_utils.py
- utils/pdf_utils.py
**READY**
Fixed `cStringIO` imports to make it compatible with Python 2.x and Python 3.x
`cStringIO` module changed to `io.StringIO` in Python 3.
Used `six` package to import which is a compatibility layer for Python 2 and 3 apps.
> fix: 🐛 Make StringIO imports python 2 and 3 compatible

- apps/accounts/utils/auth.py
- apps/accounts/utils/general.py
- apps/async_task/utils.py
- compat.py
- lib/dynamic_screening_solutions/api.py
- lib/dynamic_screening_solutions/utils.py
- lib/fitbit/api.py
- lib/google/gmail/api.py
- lib/zillow/zestimate.py
- lib/zillow/zillow_types.py
- templatetags/htk_tags.py
- templatetags/urlizer.py
- utils/crypto.py
- views.py
**READY**
`base64.b64encode` requires encoded `bytes` in Python 3 but it works with `str` in Python 2.
The result of this function is `bytes` in Python 3 and `str` in Python 2.
Encoding the data with `utf-8` before passing to `base64.b64encode` works both for Python 2 and 3.
If the returning value is `bytes` (this only happens with Python 3) it needs to be decoded with `utf-8`
> refactor: ♻️ Make b64encode Python 2/3 compat

- apps/changelog/management/commands/changelog.py
- compat.py
- lib/dynamic_screening_solutions/utils.py
**READY**
- Fixes a typo in `compat.py`
- Fixes a sad path in 321 webhook request validator.
- Makes the `hmac.new` Python 2/3 compatible. (It accepts `bytes` for 1st and 2nd arguments)
It seems, there are times that `hash_key` is None. The code before was not handling that correctly.
> fix: 🐛 321Forms webhook event hasher

- lib/dynamic_screening_solutions/utils.py
**READY**
Fixed a typo in function parameter name
> fix: 🐛 Typo on 321Forms hash method

- lib/dynamic_screening_solutions/utils.py
**READY**
- Fixed `hash_key` type for Python 2
Did an extensive testing:
1. First tried with `str`:
```sh
>>> key = 'some-hard-to-guess-key'
>>> msg = 'some-importang-msg-to-hash-or-something'
>>> hmac.new(key, msg, digestmod=hashlib.sha1).digest()
']h\x94\\\xd7\xda\xc7oM\x08!J\xcc\x93\xdb.`\x87\xc2\xb1'
```
2. Tried with only making `key` `unicode`:
```sh
>>> key = u'some-hard-to-guess-key'
>>> hmac.new(key, msg, digestmod=hashlib.sha1).digest()
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/usr/lib/python2.7/hmac.py", line 136, in new
return HMAC(key, msg, digestmod)
File "/usr/lib/python2.7/hmac.py", line 75, in __init__
self.outer.update(key.translate(trans_5C))
TypeError: character mapping must return integer, None or unicode
```
3. Tried with making …
> fix: 🐛 Convert the hash_key to bytes in Python 2

- compat.py
- utils/crypto.py
**READY**
- Fixed `decrypt` method of `AESCipher` to make it compatible with Python 3.
It was decoding with `base64.b64decode` in Python 2. I updated it to `htk.compat.b64decode` but it needs to stay as bytes for `decrypt`ing to work.
**NOTE:** Tested with Python 2.7 and Python 3.9
> refactor: ♻️ AESCipher Python 2/3 compatability

- lib/dynamic_screening_solutions/utils.py
**READY**
- Fixed a check where `request.body` being a `bytes`.
> fix: 🐛 validate_webhook_request trying to encode `bytes`

- apps/organizations/models.py
- extensions/data_structures/ordered_set.py
- utils/cache_descriptors.py
The issue is importing modules of `Collections` differs based on Python version.
Used library `six`  for Python 2 and 3 compatability.
> Fix issue module collections compatible for Python 2 and Python 3

- apps/accounts/utils/general.py
- compat.py
- lib/slack/beacon/utils.py
- test_scaffold/utils.py
This PR fixes the issue `'UUID' object has no attribute 'get_hex'`.
In Python 2 `UUID` has method `get_hex()` which doesn't exist in Python 3.
Instead, the `hex` attribute should be used.
A Python 2/3 compatibility util, `uuid4_hex`, is introduced, to allow inter-operability.
> Fix UUID has no attribute `get_hex`

- middleware/classes.py
- Fixes `htk.middleware.classes.HttpErrorResponseMiddleware` by adding missing required methods.
> fix: 🐛 HttpErrorResponseMiddleware

- api/views.py
- fixed base filter is being excluded instead of filtering.
- `model_class` is now can be a `QuerySet` to allow special circumstances like aggregation might be needed beforehand.
> fix: 🐛 datatables api view builder

- apps/forums/models.py
- Adds a `reply_to` ForeignKey to ForumMessages to track messages that are replies to messages similar to replies on other forums such as `skool` and `reddit`. 
- Replies allow for forum users to engage in discussions under a message rather than individual messages under a thread. 
- Fixes code in the `organizations` abstract models so that the organization member can be correctly displayed when the `__str__` method is used. 
- Refer to https://docs.djangoproject.com/en/dev/ref/models/fields/#django.db.models.ForeignKey for more information on the usage of foreign keys in Django models.
> ✨ : updates `ForumMessage` model with foreign key `reply_to`

- lib/stripe_lib/models.py
Handle to remove already `canceled` Stripe subscriptions that happened may be due to `Stripe Payment Failure` or other reasons.
> Remove already canceled subscriptions

- view_helpers.py
an upgrade to pass `args` or `kwargs` to `reverse` function.
Solves the following case:
URL definition:
```python
from django.urls import re_path
urlpatterns = [
re_path(r'^(?P<type>privacy|tos)$', ..., name='policy')
]
```
Usage:
```python
from htk.view_helpers import generate_nav_links
generate_nav_links([
{
'text': 'Privacy Policy',
'url_name': 'policies:policy',
'args': ('privacy',),
},
{
'text': 'Terms of Service',
'url_name': 'policies:policy',
'args': ('tos',),
},
])
```
> feat: ✨ upgrade generate_nav_links view helper

- apps/conversations/models.py
- Uses the `as_dict` method with a `user.profile` instead of `user` in the `ConversationReaction`s model.
> fix: 🔧 modifies `as_dict` model method in the `reactions` model

- test_scaffold/utils.py
- Adds `should_associate_user_email` optional field to associate a `UserEmail` email to a test user created in `test_scaffold`.
> feat: ✨ adds additional email association` field to `create_test_user()`

- apps/prelaunch/utils.py
Django cannot receive cookie data from the react-native environment.
Instead of adding it as a query-parameter on every request, sending it in the header was better.
This PR updates the `get_early_access_code` helper function to also get the early access code from header.
> feat: add ability to recognize early access code in header

- apps/prelaunch/models/base.py
- utils/notifications.py
- Removes the explicit level `info` and uses the default level `debug` for the early access notification. 
- Default notification level: https://github.com/hacktoolkit/django-htk/blob/a3043a0dc859282f35827bb1dbd2cd81fd17eec1/utils/notifications.py#L37-L39
> fix: 🔧 changes `early access` notification channel from `p4` to `p5` for dev and test servers

- constants/defaults.py
- Adds missing blob constant https://github.com/hacktoolkit/django-htk/blob/2ba2a0a6467c06ec5c308c9267ad43d553232750/apps/blob_storage/constants/defaults.py import in the main constants `defaults` file used by `htk_setting`. 
- Allows other apps to successfully use the `setting` for `'HTK_BLOB_CONTENT_MAX_LENGTH'`
> fix: 🔧 adds `blob` max size to main constants

- lib/google/youtube/utils.py
Update the regex to include `YouTube Shorts URL(s)` for extracting `YouTube video ID`.
> Include YouTube shorts URL(s) for video ID extraction

- apps/accounts/constants/defaults.py
- apps/accounts/social_auth_pipeline.py
Allows desired social auth backends to be defined as auto-associate. This will allow to associate social accounts with existing accounts in the pipeline automatically.
> feat: ✨ social-auth auto associate existing user

- api/auth/__init__.py
- api/auth/requests.py
- lib/indeed/__init__.py
- lib/indeed/api.py
- lib/indeed/constants.py
API to post the disposition status of applications received through Indeed.
> Indeed disposition sync api

- apps/accounts/models.py
- Fixes a typo with the reference to the `profile user` when checking if the user is a member of an `organization`.
> fix: 🔧 `profile user` reference in `is_organization_member`

- utils/notifications.py
- Adds a new parameter to specify a custom Slack channel for sending the message, which takes precedence over other configured levels.
> feat: ✨ adds a custom channel parameter to `slack_notify`

- apps/blob_storage/models.py
To make the files editable in the Django admin this small addition needed.
`editable` option is `False` by default for `BinaryField`
> feat: ✨ Make file blob contents editable

- middleware/__init__.py
- middleware/classes.py
- Adds `RequestTooBig` Middleware  to detect when the `request.body` triggers a `RequestDataTooBig` exception and returns a custom `JSON 400` response. 
- The location where the request.body validation occurs: https://github.com/django/django/blob/5f30fd2358fd60a514bdba31594bfc8122f30167/django/http/request.py#L368-L375
> feat: ✨ adds a `RequestTooBig` Middleware to detect large request bodies

- apps/accounts/middleware.py
- apps/accounts/utils/general.py
- utils/request.py
The main purpose of this PR is to give room to custom authentication middlewares in the projects.
The middlewares were cutting off the execution and giving forbidden errors other than the `Bearer` and `Basic` auth token types.
Also getting the `token_type` and `token` from `HTTP_AUTHORIZATION` is made a utility function to keep the code DRY.
> feat: ✨ update auth middlewares to allow other auth middlewares

- apps/organizations/models.py
- Fixes the incorrect `related_name` for the `user foreign key` on the `organization member`.
> fix: 🔧  related name for `organization members`

- lib/github/models/release.py
- lib/github/utils.py
- Removes the invalid ordering key called `version` which doesn't exist on the model and uses `published_at` instead. 
- Cleans up leftover code and imports.
> fix: 🔧 uses `published_at` as the key when ordering `releases`

- utils/enums.py
This is especially helpful for displaying human-readable enums within Django templates. For example, let's say there's an object with a `status` enum property of a Model. So we define a `status_enum` on the model, and then within the Django template, we can use `model_instance.status_enum.display` to render the human-readable string.
> feat: Add `display` property to `HtkEnum` for symbolic name retrieval

- apps/blob_storage/models.py
Added the ability to store binary data/blob temporarily with a URL link.
> feat: ✨ added cors headers for share images

- apps/assessments/models.py
- Adds new fields to the `AssessmentQuestion` model to specify max and min number of choices for choice based assessment questions.
> feat: ✨ adds min and max choices for `AssessmentQuestion`s

- apps/assessments/models.py
- Adds an `allow_free_response boolean` field to `AbstractAssessmentQuestionAnswerOption` to enable conditional free-text input for specific multiple-choice options.
- Enables "Other (please specify)" style options in multiple-choice questions where users can:
- Select the option (e.g., "Other")
- Provide additional free-text details in the same response
> feat: ✨ adds field `allow_free_response` on `AssessmentQuestionAnswerOption` model
